version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./:/go/app
    command: air
    ports:
      - 8888:8888
      - 2345:2345
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - REGION
      - USER_POOL_ID
      - USER_POOL_WEB_CLIENT_ID
      - TEST_EMAIL
      - TEST_PASSWORD
