.PHONY: lint test test-ci

lint:
	@go vet ./...
	@golangci-lint run ./...
format:
	@gofmt -l -s -w .
	@goimports -w -l ./
test:
	@go test -v ./...
test-ci:
	@go test -v -coverprofile coverage.out -covermode atomic ./...
