name: ci-master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Docker set up
        run: |
          cp .air.normal.conf .air.conf
          docker-compose up --build -d
      - name: Execute test
        run: |
          docker-compose exec -T api make lint
          docker-compose exec -T api make test-ci
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
